server:
  port: 13000

spring:
  application:
    name: message-system-consumer
  
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.114:8848

# Dubbo配置
dubbo:
  application:
    name: message-system-consumer
  registry:
    address: nacos://192.168.1.114:8848
  consumer:
    check: false
    timeout: 30000

# 日志配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
